version: '3.3'
services:
  ###########################################################
  ###################     DATABASE    #######################
  ###########################################################
  db:
    image: library/postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports: ["5432:5432"]

volumes:
  db_data: